const SearchData = [
  {
    id: 1,
    title: 'Late Night With Seth Myers',
    url: 'https://www.youtube.com/embed/tgbNymZ7vqY',
    description: 'Twinkle Twinkle little star',
    date: '2015-04-07T03:00:03.000Z',
  },
  {
    id: 2,
    title: 'The Daily Show With Trevor Noah',
    url: 'https://www.youtube.com/embed/tgbNymZ7vqY',
    description: 'How I wonder what you are',
    date: '2015-04-08T03:00:03.000Z',
  },
  {
    id: 3,
    title: 'The Late Show With Stephen Colbert',
    url: 'https://www.youtube.com/embed/tgbNymZ7vqY',
    description: 'Up above the worlds so high',
    date: '2015-04-09T03:00:03.000Z',
  },
  {
    id: 4,
    title: 'The Late Show With Stephen Colbert',
    url: 'https://www.youtube.com/embed/tgbNymZ7vqY',
    description: 'Like a diamond in the sky',
    date: '2015-04-10T03:00:03.000Z',
  },
  {
    id: 5,
    title: 'The Late Show With Stephen Colbert',
    url: 'https://www.youtube.com/embed/tgbNymZ7vqY',
    description: 'Ba ba black sheep have you any wool',
    date: '2015-04-11T03:00:03.000Z',
  },
  {
    id: 6,
    title: 'The Late Show With Stephen Colbert',
    url: 'https://www.youtube.com/embed/tgbNymZ7vqY',
    description: 'Yes sir yes sir three bags full',
    date: '2015-04-12T03:00:03.000Z',
  },
  {
    id: 7,
    title: 'The Late Show With Stephen Colbert',
    url: 'https://www.youtube.com/embed/tgbNymZ7vqY',
    description: 'one for my master one for the dame ',
    date: '2015-04-13T03:00:03.000Z',
  },
  {
    id: 8,
    title: 'The Late Show With Stephen Colbert',
    url: 'https://www.youtube.com/embed/tgbNymZ7vqY',
    description: 'one for the little boy who leaves down the lane ',
    date: '2015-04-14T03:00:03.000Z',
  },
  {
    id: 9,
    title: 'The Late Show With Stephen Colbert',
    url: 'https://www.youtube.com/embed/tgbNymZ7vqY',
    description: 'row row row your boat gently down the stream',
    date: '2015-04-15T03:00:03.000Z',
  },
  {
    id: 10,
    title: 'The Late Show With Stephen Colbert',
    url: 'https://www.youtube.com/embed/tgbNymZ7vqY',
    description: 'merrily merrily merrily merilly life is but a dream',
    date: '2015-04-16T03:00:03.000Z',
  },
  {
    id: 11,
    title: 'The Late Show With Stephen Colbert',
    url: 'https://www.youtube.com/embed/tgbNymZ7vqY',
    description: 'row row row your boat gently down the stream2',
    date: '2015-04-17T03:00:03.000Z',
  },
  {
    id: 12,
    title: 'The Late Show With Stephen Colbert',
    url: 'https://www.youtube.com/embed/tgbNymZ7vqY',
    description: 'if you see a crocodile dont forget to scream',
    date: '2015-04-18T03:00:03.000Z',
  },
  {
    id: 13,
    title: 'The Late Show With Stephen Colbert',
    url: 'https://www.youtube.com/embed/tgbNymZ7vqY',
    description: 'johny johny yes papa ',
    date: '2015-04-19T03:00:03.000Z',
  },
  {
    id: 14,
    title: 'The Late Show With Stephen Colbert',
    url: 'https://www.youtube.com/embed/tgbNymZ7vqY',
    description: 'eating sugar no papa',
    date: '2015-04-20T03:00:03.000Z',
  },
  {
    id: 15,
    title: 'The Late Show With Stephen Colbert',
    url: 'https://www.youtube.com/embed/tgbNymZ7vqY',
    description: 'telling lies no papa',
    date: '2015-04-21T03:00:03.000Z',
  },
  {
    id: 16,
    title: 'The Late Show With Stephen Colbert',
    url: 'https://www.youtube.com/embed/tgbNymZ7vqY',
    description: 'open your mouth ha ha ha',
    date: '2015-04-22T03:00:03.000Z',
  },
];
export default SearchData;
